server:
  port: 8761

spring:
  application:
    name: msvc-eureka
  config:
    import: optional:configserver:http://localhost8088

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-register: false
    server-url:
      defaultZone: http://localhost:${server.port}/eureka



